Update deployment-mysql-alive.yml

diff --git a/.github/workflows/deployment-mysql-alive.yml b/.github/workflows/deployment-mysql-alive.yml
--- a/.github/workflows/deployment-mysql-alive.yml
+++ b/.github/workflows/deployment-mysql-alive.yml
@@ -18,7 +18,43 @@ jobs:
           UNIQUE_TAG=$(git rev-parse --short HEAD)
           echo "UNIQUE_TAG=${UNIQUE_TAG}" >> $GITHUB_OUTPUT
 
+
   job2:
+    runs-on: ubuntu-latest
+    needs: job1
+    steps:
+      - name: Use tag from job1
+        run: |
+          echo "Using tag: ${{ needs.job1.outputs.UNIQUE_TAG }}"
+        # Step 2: Authenticate with Docker Hub
+      - name: Authenticate with Docker Hub
+        env:
+          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+        run: |
+          echo "${DOCKERHUB_TOKEN}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
+          if [ $? -eq 0 ]; then
+            echo "Successfully authenticated with Docker Hub"
+          else
+            echo "Authentication failed"
+            exit 1
+          fi            
+
+      # Step 3: Build the Docker image
+      - name: Build Docker image
+        run: |
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ needs.job1.outputs.UNIQUE_TAG }} .
+
+      # Step 4: Push the Docker image to Docker Hub
+      - name: Push Docker image to Docker Hub
+        run: |
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ needs.job1.outputs.UNIQUE_TAG }}          
+
+      # Step 5: Logout from Docker Hub (optional cleanup)
+      - name: Logout from Docker Hub
+        run: |
+          docker logout   
+  job3:
     needs: job1
     runs-on: ubuntu-latest
     steps:
